config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#index'

  resources :products

  resources :baskets, only: %i[show destroy]

  resources :line_items, only: %i[create update destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
# frozen_string_literal: true

class Basket < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  def sub_total
    line_items.inject(0) do |sum, line_item|
      sum + line_item.total_price
    end
  end
end

app/models/discount.rb
# frozen_string_literal: true

class Discount < ApplicationRecord
  belongs_to :product

  validates :name,
            presence: true,
            uniqueness: { scope: %i[name product] }
  validates :priority, presence: true
  validates :quantity_condition, presence: true
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :basket
  belongs_to :product

  validates :quantity,
            presence: true,
            uniqueness: { scope: %i[basket product] }

  def total_price
    LineItems::Balance.call(line_item: self)
                      .data[:balance][:total]
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :discounts, dependent: :destroy

  validates :code, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_basket

  private

  def current_basket
    if session[:basket_id]
      basket = Basket.find_by(id: session[:basket_id])
      if basket.present?
        @current_basket = basket
      else
        session[:basket_id] = nil
      end
    end

    if session[:basket_id].nil?
      @current_basket = Basket.create
      session[:basket_id] = @current_basket.id
    end
  end
end

app/controllers/baskets_controller.rb
# frozen_string_literal: true

class BasketsController < ApplicationController
  def show
    @basket = @current_basket
  end

  def destroy
    @basket = @current_basket
    @basket.destroy
    session[:basket_id] = nil

    redirect_to root_path
  end
end

app/controllers/line_items_controller.rb
# frozen_string_literal: true

class LineItemsController < ApplicationController
  def create
    chosen_product = Product.find_by(id: params[:product_id])
    service = LineItems::Create.call(product: chosen_product, basket: @current_basket)

    if service.success?
      @line_item = service.data[:line_item]
    else
      flash[:error] = service.data[:error]
    end

    redirect_to basket_path(@current_basket)
  end

  def update
    @line_item = LineItem.find_by(id: params[:line_item_id])
    service = LineItems::Update.call(line_item: @line_item,
                                     operation: params[:operation],
                                     quantity: params[:quantity].to_i)

    flash[:error] = service.data[:error] if service.failure?

    redirect_to basket_path(@current_basket)
  end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to basket_path(@current_basket)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :code, :price)
  end
end

app/helpers/baskets_helper.rb
# frozen_string_literal: true

module BasketsHelper
end

app/helpers/line_items_helper.rb
# frozen_string_literal: true

module LineItemsHelper
end

app/views/baskets/show.html.erb
<h2>Basket</h2>

<% if @basket.line_items.where('quantity > ?', 0).present? %>
  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Price</th>
        <th id="quantity_header" colspan="1" >Quantity</th>
        <th>Total</th>
        <th>Actions</th>
        <th>Discounts</th>
      </tr>
    </thead>

    <tbody>
      <% @basket.line_items.each do |line_item| %>
        <% balance = LineItems::Balance.call(line_item: line_item).data[:balance] %>
        <tr>
          <td><%= line_item.product.name %></td>
          <td><%= number_to_currency(balance[:price]) %></td>

          <%= form_tag :line_item, :method => :put do %>
            <td class="quantity" data-product=<%="#{line_item.product.id}" %>>
              <%= number_field_tag :quantity, line_item.quantity, min: 0, step: 1 %>
            </td>

            <%= text_field_tag :line_item_id, line_item.id, class:'hidden' %>
            <%= text_field_tag :operation, 'update', class:'hidden' %>
            <%= text_field_tag :product_id, line_item.product.id, class:'hidden' %>

            <td id=<%="update_quantity_product_#{line_item.product.id}"%> class='hidden' >
              <%= submit_tag 'Save', class: 'btn' %>
            </td>
          <% end %>

          <td><%= number_to_currency(balance[:total])  %></td>
          <td><%= link_to "Delete", line_item_path(line_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% if balance[:discount] %>
            <td> <%= balance[:discount] %> </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h3>Sub total: <%= number_to_currency(@basket.sub_total) %></h3>

  <%= link_to "Empty basket", basket_path(@current_basket), method: :delete, data: {confirm: "Are you sure?"}%>
  <br>
  <br>

<% else %>
  <h2>
    Your basket it's empty
  </h2>
<% end %>

<%= link_to "Products", products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CashRegister</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Price</th>
      <th>Basket</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.code %></td>
        <td><%= product.price %></td>
        <% line_item = @current_basket&.line_items&.find_by(product: product) %>
        <% if line_item.present? %>
          <td><%= button_to "Add to basket", line_item_path(operation: 'add', id: line_item.id, product_id: product.id), method: :put %></td>
        <% else %>
          <td><%= button_to "Add to basket", line_items_path(product_id: product.id) %></td>
        <% end %>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Basket", basket_path(@current_basket) %>
<br>
<br>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @product.code %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>